server:
  port: 7001
  context-path: /

eureka:
  instance:
    hostname: eureka7001.com
    prefer-ip-address: false
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心 只需要维护服务实例 不需要检索服务
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与eureka server交互的地址查询服务和注册服务
       defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      
security:
  enable-csrf: false