server:
  port: 9527

spring:
  application:
    name: spring-cloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: alicyu-microcloud
  company.name: www.alicyu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
zuul:
  ignored-services: "*"
  routes:
    mydept.serviceId: spring-cloud-dept
    mydept.path: /mydept/**
  prefix: /jay